#!/bin/bash

player_names=(
    "Din"
    "Zorina"
    "Stephana"
    "Aurlie"
    "Verene"
    "Ingra"
    "Merlina"
    "Marius"
    "Mattie"
    "Sydel"
    "Pearla"
    "Rowen"
    "Emilie"
    "Kip"
    "Catherina"
    "Lodovico"
    "Wang"
    "Roseanna"
    "Gothart"
    "Ker"
    "Hinze"
    "Jonis"
    "Birgitta"
    "Mike"
    "Shermy"
    "Fidelia"
    "Beulah"
    "Keir"
    "Cosmo"
    "Carmelina"
    "Dorine"
    "Dedie"
    "Whit"
    "Dorena"
    "Wiatt"
    "Roland"
    "Engracia"
    "Maurene"
    "Cass"
    "Artemis"
    "Mahalia"
    "Tomaso"
    "Rube"
    "Merle"
    "Agathe"
    "Pace"
    "Noelani"
    "Aurie"
    "Jerrine"
    "Felicity"
    "Ricoriki"
    "Henri"
    "Darcie"
    "Kathryn"
    "Farleigh"
    "Manolo"
    "Letitia"
    "Celisse"
    "Joshia"
    "Briney"
    "Hobey"
    "Paddy"
    "Gayel"
    "Muire"
    "Willy"
    "Meris"
    "Hester"
    "Josephina"
    "Bryn"
    "Cornie"
    "Irwinn"
    "Melosa"
    "Mervin"
    "Katha"
    "Richardo"
    "Karlik"
    "Helen-elizabeth"
    "Dori"
    "Sanford"
    "Gregoor"
    "Cthrine"
    "Sunny"
    "Chandler"
    "Eleonora"
    "Eb"
    "Phylys"
    "Bryn"
    "Samantha"
    "Obed"
    "Jeremiah"
    "Alfie"
    "Tanney"
    "Gianna"
    "Ewen"
    "Lilas"
    "Norbert"
    "Gustave"
    "Lianne"
    "Stefanie"
    "Cati"
)

echo "<odoo>"
echo "<data>"

while read line
do
    character_name=$(echo $line)
    echo "<record id='character$character_name' model='bruto_arena.character'>"
    echo "<field name='name'>$character_name</field>"
    echo "<field name='player' ref='bruto_arena.player${player_names[(RANDOM % 100)]}'></field>"
    echo "<field name='experience'>$((RANDOM % 100000))</field>"
    echo "</record>"
done

echo "</data>"
echo "</odoo>"